import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer";
import BackToTop from "@/components/back-to-top";
import GuaranteeSection from "@/components/guarantee-section";
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Shop Glasses Online | Save up to 50% OFF + Free Shipping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> 
          <CartProvider>
            <div className="mx-auto w-full">
              <Navbar />
              {children}
              <BackToTop />
              <GuaranteeSection />
              <Footer />
            </div>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
